project_id = "oxymhnddzamsjxwfglud"

[functions.company-asaas-api]
verify_jwt = false

[functions.company-asaas-webhook]
verify_jwt = false

[functions.ai-classify-personal]
verify_jwt = false

[functions.ocr-document]
verify_jwt = false

[functions.owner-transactions]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.reconcile-transactions]
verify_jwt = false

[functions.list-whatsapp-groups]
verify_jwt = false
